# Generated by Django 5.2.3 on 2026-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregtxtss',
            name='alternativa',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Alternativa'),
        ),
        migrations.AddField(
            model_name='regtxtss',
            name='alternativa',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Alternativa'),
        ),
    ]
