# Generated by Django 5.2.3 on 2026-05-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0003_add_alternativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregtxtss',
            name='alternativa',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1, verbose_name='Alternativa'),
        ),
        migrations.AlterField(
            model_name='regtxtss',
            name='alternativa',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1, verbose_name='Alternativa'),
        ),
    ]
