# Generated by Django 5.2.3 on 2026-05-16 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contractor_add_is_deleted'),
        ('reg_txtss', '0004_alternativa_default_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regtxtss',
            constraint=models.UniqueConstraint(fields=('sitio', 'user', 'fecha', 'alternativa'), name='unique_sitio_user_fecha_alternativa_regtxtss'),
        ),
    ]
