# Generated by Django 5.2.3 on 2026-05-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0005_alternativa_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregtxtss',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalregtxtss',
            name='title',
        ),
        migrations.RemoveField(
            model_name='regtxtss',
            name='description',
        ),
        migrations.RemoveField(
            model_name='regtxtss',
            name='title',
        ),
    ]
