# Generated by Django 5.2.3 on 2026-05-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0006_remove_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregtxtss',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluido'),
        ),
        migrations.AddField(
            model_name='regtxtss',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluido'),
        ),
    ]
