# Generated by Django 5.2.3 on 2026-05-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0007_add_concluido_to_regtxtss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rempalme',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='rsitio',
            name='registro',
        ),
        migrations.DeleteModel(
            name='RAcceso',
        ),
        migrations.DeleteModel(
            name='REmpalme',
        ),
        migrations.DeleteModel(
            name='RSitio',
        ),
    ]
