# Generated by Django 5.2.3 on 2026-05-15 13:55

from django.db import migrations, models


def admin_to_coord(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(user_type='ADMIN').update(user_type='COORD')


def coord_to_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(user_type='COORD').update(user_type='ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('COORD', 'Coordinador'), ('MANAGER', 'Manager'), ('ITO', 'Inspector Técnico de Obra'), ('SEARCHER', 'Buscador'), ('CLIENT', 'Cliente')], default='ITO', max_length=50, verbose_name='Tipo de Usuario'),
        ),
        migrations.RunPython(admin_to_coord, reverse_code=coord_to_admin),
    ]
