# Generated by Django 5.2.3 on 2026-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('GERENCIA', 'Gerencia'), ('COORD', 'Coordinador'), ('ITO', 'ITO'), ('SEARCHER', 'Buscador'), ('VISITA', 'Visita')], default='ITO', max_length=50, verbose_name='Tipo de Usuario'),
        ),
    ]
