# Generated by Django 5.2.3 on 2026-05-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contractor_add_is_deleted'),
        ('users', '0004_user_type_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.contractor', verbose_name='Empresa'),
        ),
    ]
