# Generated by Django 5.2.3 on 2026-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_contractor_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_access',
            field=models.JSONField(blank=True, default=list, help_text='Lista de reportes permitidos. Vacío = acceso total.', verbose_name='Acceso a Reportes'),
        ),
    ]
