# Generated by Django 5.2.3 on 2026-05-16 21:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_contractor_add_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaWidgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Fila de Widgets',
                'verbose_name_plural': 'Filas de Widgets',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PasoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.SlugField(verbose_name='Nombre (slug)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Paso de Actividad',
                'verbose_name_plural': 'Pasos de Actividad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('app_namespace', models.SlugField(unique=True, verbose_name='Namespace URL')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfigWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FORM', 'Formulario'), ('MAP_1', 'Mapa 1 punto'), ('MAP_2', 'Mapa 2 puntos'), ('MAP_3', 'Mapa 3 puntos'), ('CAMERA', 'Cámara / fotos')], max_length=20, verbose_name='Tipo de widget')),
                ('orden_en_fila', models.PositiveIntegerField(default=0, verbose_name='Orden en fila')),
                ('params', models.JSONField(blank=True, default=dict, help_text='CAMERA: {"label": "Fotos", "foto_min": 2} | MAP_1: {"label": "Ubicación"}', verbose_name='Parámetros')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='actividades.filawidgets')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['orden_en_fila'],
            },
        ),
        migrations.AddField(
            model_name='filawidgets',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='actividades.pasoactividad'),
        ),
        migrations.CreateModel(
            name='RegActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site', verbose_name='Sitio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.tipoactividad', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pasoactividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='actividades.tipoactividad'),
        ),
        migrations.CreateModel(
            name='DatoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('paso_nombre', models.CharField(max_length=50, verbose_name='Nombre del paso')),
                ('datos', models.JSONField(default=dict, verbose_name='Datos (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Dato de Paso',
                'verbose_name_plural': 'Datos de Pasos',
                'unique_together': {('content_type', 'object_id', 'paso_nombre')},
            },
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre (clave JSON)')),
                ('etiqueta', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto corto'), ('TEXTAREA', 'Texto largo'), ('INTEGER', 'Número entero'), ('FLOAT', 'Número decimal'), ('DECIMAL', 'Decimal con precisión'), ('PORCENTAJE', 'Porcentaje (0–100)'), ('DATE', 'Fecha'), ('SELECT', 'Selección (opciones)'), ('BOOLEAN', 'Sí / No'), ('LAT', 'Latitud'), ('LON', 'Longitud')], max_length=20, verbose_name='Tipo')),
                ('requerido', models.BooleanField(default=True, verbose_name='Requerido')),
                ('ayuda', models.CharField(blank=True, max_length=200, verbose_name='Texto de ayuda')),
                ('placeholder', models.CharField(blank=True, max_length=100, verbose_name='Placeholder')),
                ('unidad', models.CharField(blank=True, max_length=20, verbose_name='Unidad (ej: metros, %)')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud máx. (TEXT)')),
                ('min_valor', models.FloatField(blank=True, null=True, verbose_name='Valor mínimo')),
                ('max_valor', models.FloatField(blank=True, null=True, verbose_name='Valor máximo')),
                ('opciones', models.JSONField(blank=True, default=list, help_text='JSON: [{"valor": "A", "label": "Opción A"}, ...]', verbose_name='Opciones (SELECT)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='actividades.pasoactividad')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
                'ordering': ['orden'],
                'unique_together': {('paso', 'nombre')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pasoactividad',
            unique_together={('tipo', 'nombre')},
        ),
    ]
