# Generated by Django 5.2.3 on 2026-05-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='tipo_sitio',
            field=models.CharField(blank=True, choices=[('POSTE', 'Poste'), ('TORRE', 'Torre')], help_text='Dejar vacío si aplica a todos los tipos de sitio.', max_length=10, null=True, verbose_name='Tipo de sitio'),
        ),
    ]
