# Generated by Django 5.2.3 on 2026-05-17 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_campo_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoformulario',
            name='js_code',
            field=models.TextField(blank=True, help_text='Código JS ejecutado al hacer clic en el botón', verbose_name='JavaScript (BUTTON)'),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='opciones',
            field=models.JSONField(blank=True, default=list, help_text='Una por línea: valor|etiqueta', verbose_name='Opciones (SELECT)'),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden en fila'),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto corto'), ('TEXTAREA', 'Texto largo'), ('INTEGER', 'Número entero'), ('FLOAT', 'Número decimal'), ('DECIMAL', 'Decimal con precisión'), ('PORCENTAJE', 'Porcentaje (0–100)'), ('DATE', 'Fecha'), ('SELECT', 'Selección (opciones)'), ('BOOLEAN', 'Sí / No'), ('LAT', 'Latitud'), ('LON', 'Longitud'), ('BUTTON', 'Botón / Acción')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='configwidget',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='actividades.pasoactividad'),
        ),
    ]
