# Generated by Django 5.2.3 on 2026-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_campo_js_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoformulario',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto corto'), ('TEXTAREA', 'Texto largo'), ('INTEGER', 'Número entero'), ('FLOAT', 'Número decimal'), ('DECIMAL', 'Decimal con precisión'), ('PORCENTAJE', 'Porcentaje (0–100)'), ('DATE', 'Fecha'), ('SELECT', 'Selección (opciones)'), ('BOOLEAN', 'Sí / No'), ('LAT', 'Latitud'), ('LON', 'Longitud'), ('BUTTON', 'Botón / Acción'), ('TEXT_BTN', 'Texto + Botón de acción')], max_length=20, verbose_name='Tipo'),
        ),
    ]
