# Generated by Django 5.2.3 on 2026-05-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_paso_definicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configwidget',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='actividades.pasodefinicion'),
        ),
    ]
