# Generated by Django 5.2.3 on 2026-05-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_widgetdefinicion_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='configwidget',
            name='min_fotos',
            field=models.PositiveIntegerField(default=0, help_text='Solo aplica para widgets de tipo Cámara. 0 = sin mínimo.', verbose_name='Mínimo de fotos'),
        ),
    ]
