# Generated by Django 5.2.3 on 2026-05-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_configwidget_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configwidget',
            name='paso',
        ),
        migrations.RemoveField(
            model_name='configwidget',
            name='widgetdef',
        ),
        migrations.DeleteModel(
            name='CampoFormulario',
        ),
        migrations.DeleteModel(
            name='ConfigWidget',
        ),
        migrations.DeleteModel(
            name='WidgetDefinicion',
        ),
    ]
