# Generated by Django 5.2.3 on 2026-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_drop_widget_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasodefinicion',
            name='widget_slug',
            field=models.CharField(blank=True, default='', help_text='Slug del template de widget (ej. camera_widget).', max_length=100, verbose_name='Widget'),
        ),
    ]
