# Generated by Django 5.2.3 on 2026-05-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0018_paso_definicion_widget_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasodefinicion',
            name='widget_slug',
        ),
        migrations.CreateModel(
            name='PasoWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_slug', models.CharField(max_length=100, verbose_name='Widget')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pasodef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paso_widgets', to='actividades.pasodefinicion', verbose_name='Paso')),
            ],
            options={
                'verbose_name': 'Widget de paso',
                'verbose_name_plural': 'Widgets de paso',
                'ordering': ['orden'],
                'unique_together': {('pasodef', 'widget_slug')},
            },
        ),
    ]
