# Generated by Django 5.2.3 on 2026-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0019_paso_widget_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasowidget',
            name='config',
            field=models.JSONField(default=dict, verbose_name='Configuración'),
        ),
        migrations.AlterField(
            model_name='pasodefinicion',
            name='nombre',
            field=models.SlugField(verbose_name='Nombre (slug)'),
        ),
    ]
