# Generated by Django 5.2.3 on 2026-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0020_pasowidget_config_pasodefinicion_nonunique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegActividad',
        ),
    ]
