# Generated by Django 5.2.3 on 2026-05-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_split_lat_lon_into_3_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='lat_inspeccion',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud Inspección'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='lon_inspeccion',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud Inspección'),
        ),
        migrations.AddField(
            model_name='site',
            name='lat_inspeccion',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud Inspección'),
        ),
        migrations.AddField(
            model_name='site',
            name='lon_inspeccion',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud Inspección'),
        ),
    ]
