# Generated by Django 5.2.3 on 2026-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_inspeccion_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='tipo_sitio',
            field=models.CharField(choices=[('POSTE', 'Poste'), ('TORRE', 'Torre')], default='TORRE', max_length=10, verbose_name='Tipo de sitio'),
        ),
        migrations.AddField(
            model_name='site',
            name='tipo_sitio',
            field=models.CharField(choices=[('POSTE', 'Poste'), ('TORRE', 'Torre')], default='TORRE', max_length=10, verbose_name='Tipo de sitio'),
        ),
    ]
