# Generated by Django 5.2.3 on 2026-05-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_tipo_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete: el contratista no aparece en la lista', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='historicalcontractor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete: el contratista no aparece en la lista', verbose_name='Eliminado'),
        ),
    ]
