# Generated by Django 5.2.3 on 2026-05-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contractor_add_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='lat_inspeccion',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='lon_inspeccion',
        ),
        migrations.RemoveField(
            model_name='site',
            name='lat_inspeccion',
        ),
        migrations.RemoveField(
            model_name='site',
            name='lon_inspeccion',
        ),
    ]
