# Generated by Django 5.2.3 on 2026-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_inspeccion_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='empresa_energia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa de Energía'),
        ),
        migrations.AddField(
            model_name='site',
            name='empresa_energia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa de Energía'),
        ),
    ]
