# Generated by Django 5.2.3 on 2026-05-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_empresa_energia_to_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='empresa_energia',
        ),
        migrations.RemoveField(
            model_name='site',
            name='empresa_energia',
        ),
    ]
