# Generated by Django 5.2.3 on 2026-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitiodashboard',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='sitiodashboard',
            name='porcentaje_avance',
        ),
        migrations.RemoveField(
            model_name='sitiodashboard',
            name='total_registros_construccion',
        ),
        migrations.RemoveField(
            model_name='sitiodashboard',
            name='ultimo_registro_construccion',
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_type',
            field=models.CharField(choices=[('sitios_totales', 'Sitios Totales'), ('registros_txtss', 'Registros TXTSS'), ('usuarios_activos', 'Usuarios Activos')], max_length=50, unique=True),
        ),
    ]
