# Generated by Django 5.2.3 on 2026-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='exif_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora EXIF'),
        ),
        migrations.AddField(
            model_name='photos',
            name='exif_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud EXIF'),
        ),
        migrations.AddField(
            model_name='photos',
            name='exif_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud EXIF'),
        ),
    ]
