# Generated by Django 5.2.3 on 2026-05-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_exif_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)'),
        ),
    ]
