# Generated by Django 5.2.3 on 2026-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_backfill_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbs/', verbose_name='Miniatura'),
        ),
    ]
